<?xml version = "1.0" ?>
<MessageModule name = "ClcUtil">
	<Message id = "DSCALC_NOT_RUNNING" message = "Remote DsCalc not running on host %1" type = "user" />
	<Message id = "INCOMPATIBLE_SNAPSHOT_VERSION" type='user'  message="Incompatible version %1 of snapshot file %2, it should be %3." />
	<Message id = "JOB_ALREADY_QUEUED" type='user'  message="Job '%1' is already queued." />
</MessageModule>

