<?xml version = "1.0" ?>
<MessageModule name = "FPMClient">

	<Message id = "UNKNOWN_ATTRIBUTE"
		message = "Unknown attribute: '%1'"/>
	<Message id = "UNKNOWN_ATTRIBUTE_ID"
		message = "Unknown attribute-id: %1"/>

	<Message id = "ATTRIBUTE_NOT_SINGLE_VALUED"
		message = "Attribute '%1' in class '%2' is not single-valued."/>

	<Message id = "HANDLE_ID_DOES_NOT_REFER_TO_EXPECTED"
		message = "Handle id %1 does not refer to %2"/>
	<Message id = "CANNOT_ADD_SETVALUE_TO_RANGEVALUEDOMAIN"
		message = "Cannot add set value to range value domain of %1"/>

	<Message id = "ATTRIBUTE_NOT_FOUND_IN_CLASS"
		message = "Attribute '%1' not found in class '%2'"/>
	<Message id = "CANNOT_GET_ATTRVALUE_OF_REPOSITORY_OBJECT"
		message = "Cannot get value of attribute '%1' of repository object '%2'"/>

	<Message id = "BOOLEAN_ATTRIBUTE_NOT_FOUND"
		message = "'%1' not found as a boolean-valued attribute in class '%2'"/>
	<Message id = "INTEGER_ATTRIBUTE_NOT_FOUND"
		message = "'%1' not found as an integer-valued attribute in class '%2'"/>
	<Message id = "SINGLEVALUE_ATTRIBUTE_NOT_FOUND"
		message = "'%1' not found as a single-valued attribute in class '%2'"/>

	<Message id = "BASEFEAT_INCOMPATIBLE_WITH_ATTR_OPERATION"
		message = "Base feature is incompatible with Attr/Operation"/>

	<Message id = "HANDLE_STORE_TOO_SMALL_FOR_RANGE"
		message = "Handle store too small for range of size %1"/>
	<Message id = "NO_MORE_FREE_HANDLES"
		message = "No more free handles."/>
	<Message id = "NO_RANGE_OF_FREE_HANDLES_FOUND"
		message = "No range of %1 free handles found."/>
	<Message id = "ILLEGAL_HANDLE_ID"
		message = "Illegal handle id: %1"/>
	<Message id = "ILLEGAL_ITERATOR_ID"
		message = "Illegal iterator id: %1"/>
	<Message id = "HANDLE_ID_PART_OF_ITERATOR"
		message = "Handle id %1 is part of an iterator."/>

	<Message id = "UNKNOWN_CLASS"
		message = "Unknown class: '%1'"/>
	<Message id = "UNKNOWN_TYPE_ID"
		message = "Unknown type-id: %1"/>

</MessageModule>

