<?xml version = "1.0" ?>
<MessageModule name = "FPMExport">

	<Message id ="NOT_OWNED"        message="Cannot transfer ownership to another repository, deliverable is not owned by the repository." type="user"/>
    <Message id ="REQ_TRNSF_OWNER"  message="Checked-out deliverables can only be exported with transfer of ownership." type="user" />
    <Message id ="NOT_LAST_VERSION" message="Can only transfer ownership of latest version." type="user" />
    <Message id ="EXPORT_EMPTY_ROOTFOLDER" message="Cannot export root folder '%1' because it does not contain components." type="user" />

</MessageModule>
