<?xml version = "1.0" ?>
<MessageModule name = "FPMMath">
	<Message id = "DANGLING"					message = "No version for Component '%1' found in function." /> 
	<Message id = "TABLE_COLUMN_VALUE_UNDEFINED" message = "Table column value undefined." /> 
	<Message id = "FIASTD_TYPE"					message = "FiaStd Data type '%1' can not be converted to CalcValue." />
	<Message id = "CALCVALUE_TYPE"				message = "CalcValue type '%1' can not be converted to FiaStd Data." />
	<Message id = "MATCHTYPE"					message = "Type '%1' is no interpolation type." />
	<Message id = "NOT_A_TUPLE"					message = "ValueDefinition '%1' is not a tuple." />
	<Message id = "DANGLING_TYPE"				message = "No version for Type '%1' selected." />
	<Message id = "DANGLING_VALDEF"				message = "No version for Value Definition '%1' selected." />
	<Message id = "DANGLING_VARIABLE"			message = "No version for Variable '%1' selected." />
	<Message id = "DANGLING_FUNCTION"			message = "No version for Function '%1' selected." />
	<Message id = "DANGLING_FUNCVAR"			message = "No version for Function Variable '%1' selected." />
	<Message id = "NO_TYPE_MATCH"               message = "Value type '%1' can not be converted to CalcValue type '%2'." />
	<Message id = "NO_TYPE_MATCH_NB_FIELDS"     message = "Value with %1 fields can not be converted to CalcValue with %2 fields." />
	<Message id = "NO_BEGINLIST_FOUND"			message = "No '%1' found." type = "user" />
	<Message id = "NO_ENDLIST_FOUND"			message = "No matching '%1' for '%2' found." type = "user" />
	<Message id = "UNKNOWN_TUPLE_MEMBER"		message = "'%1' is unknown as a tuple member name" type = "user" />
	<Message id = "NO_TUPLESEPARATOR_FOUND"		message = "Expected tuple member to be followed by '%1', not by '%2'" type = "user" />
	<Message id = "DANGLING_FEATURE"			message = "No version for Feature '%1' selected." />
	<Message id = "DANGLING_STR_ELM"			message = "No version for Structure Element %1 selected." />
	<Message id = "DANGLING_ERRMSG"				message = "No version for Error Message %1 selected." />
</MessageModule>
