<?xml version = "1.0" encoding="ISO-8859-1" ?>
<MessageModule name = "FPMNavigator">
	
	<Message id = "FN_TOO_MANY_ARGS"
		message = "Too many arguments for path function %1 specified."/>
	
	<Message id = "FN_TOO_FEW_ARGS"
		message = "Not enough arguments for path function %1 specified."/>
	
	<Message id = "FN_REFLIST_EXPECTED"
		message = "Argument #%2 for path function %1 should be a reference or reference list."/>
	
	<Message id = "TABLE_ID"			message = "Table Id" /> 
</MessageModule>
