<?xml version = "1.0" ?>
<MessageModule name = "PublishingCoordinator">
	<Message id = "NO_CONTEXT" message = "The context for this publication is not present." />
	<Message id = "NO_INITIAL_STATE" message = "The initial state for this publication is not present." />
	<Message id = "OBLIGATED_FLAG_MISSING" message = "An obligated flag has not been set." />
	<Message id = "SET_TARGET_DIR_FAILED" message = "Target directory assignment failed." />
	<Message id = "SET_CONTEXT_ARG_FAILED" message = "Context argument assignment failed." />
	<Message id = "INVALID_CONTEXT_ARGUMENT" message = "Context argument is not valid." />
	<Message id = "RENDERER_EVALUATION_FAILED" message = "Rendering evaluation failed." />
	<Message id = "INVALID_DOCUMENT_XML" message = "Invalid document XML." />
	<Message id = "EMPTY_DOCUMENT_XML" message = "Empty document XML." />
	<Message id = "XHTML_FILE_OPEN_FAILED" message = "Couldn't open target XHTML file for writing." />
	<Message id = "FILENAME_UNDETERMINED" message = "Couldn't determine filename for output." />
	<Message id = "FILE_ALREADY_EXISTS" message = "The specified file name already exists." />
	<Message id = "MISSING_INPUT_FILE" message = "Input file missing." />
	<Message id = "INPUT_FILE_DOES_NOT_EXIST" message = "Input file could not be located (%1)." />
	<Message id = "MISSING_TEMPLATE_FILE_PATH" message = "Template file is unspecified." />
	<Message id = "INVALID_OBJECT_CONTEXT" message = "Context object is not a (valid) component or deliverable" />
	<Message id = "GET_PXDIR_FROM_REG_FAILED" message = "Error obtaining ProductXPress installation directory from registry" />
	<Message id = "GET_PXKEY_FROM_REG_FAILED" message = "Error finding ProductXPress installation key in registry" />
	<Message id = "ERR_OPENING_INTERMEDIATEFILE" message = "Could not open intermediate file for reading" />
	<Message id = "NO_PDF_ASSOCATION" message = "There is no viewer associated with the PDF format" type="user"/>
	<Message id = "PDF_VIEWER_STARTUP_FAILED" message = "Could not start PDF Viewer. Please check if a PDF Viewer is installed." type="user"/>
	<Message id = "DOCBOOK_NOT_FOUND" message = "Could not locate docbook-xsl. Please check the installation." type="user"/>
	<Message id = "FOP_NOT_FOUND" message = "Could not locate fop.bat. Please check the installation." type="user"/>
	<Message id = "XSLTPROC_NOT_FOUND" message = "Could not locate xsltproc.exe. Please check the installation." type="user"/>
	<Message id = "NO_PROGRAM_ASSOCATION" message = "There is no program associated with format '%1'" type="user"/>
	<Message id = "PROGRAM_STARTUP_FAILED" message = "Could not start associated program for file '%1'" type="user"/>
</MessageModule>

