<?xml version = "1.0" ?>
<MessageModule name = "Px">
	<Message id = "PX_PMF_PRODUCT_NOT_FOUND_ERROR"			message = "Product %1 with deployment date %2 not found in DeploymentDates:%3" />
	<Message id = "PX_PMF_PID_ATTR_ERROR"					message = "pid attribute not found in tag: %1 of DeploymentDates file" />
	<Message id = "PX_PMF_DATE_ATTR_ERROR"					message = "date attribute %1 not found in DeploymentDates file" />
	<Message id = "PX_PMF_NAME_STATE_ERROR"					message = "Name tag must be within Product tag in DeploymentDates file" />
	<Message id = "PX_PMF_DDATE_STATE_ERROR"				message = "DeploymentDate tag must be within Product tag in DeploymentDates file" />
	<Message id = "PX_CALCID_ALREADY_MAPPED"				message = "Mapper file: CopyBook %1 is already mapped" />
	<Message id = "PX_MAPPERFILE_PARSING_STATE_ERROR"		message = "Mapper file: incorrect tag nesting" />
	<Message id = "PX_MAPPERFILE_PID_ATTR_ERROR"			message = "pid attribute not found in Mapper file" />
	<Message id = "PX_MAPPER_VALUE_ERROR"					message = "no integer found in tag IndexValue of Mapper file" />
	<Message id = "PX_ONE_MODULE"							message = "Product has %1 modules. Do not know which module to use." />
	<Message id = "PX_SUBFUNC_NOT_FOUND"					message = "Product has no SubFunction named %1." />
	<Message id = "PX_FUNC_NOT_FOUND"						message = "Product has no Function named %1." />
	<Message id = "PX_NO_VALID_INTEGER"						message = "%1 is not a valid integer." />
	<Message id = "PX_NO_SUBFUNCTIONS"						message = "CopyBook and Product have no subfunctions in common." />
	<Message id = "PX_IPDE_PRODUCT_NOT_FOUND"				message = "Pid %1 (Product %2 with deployment date %3) not found in repository" />
	<Message id = "PX_NOMAPPING"							message = "No mapping found for copybook %1." />
	<Message id = "PX_INVALID_PID"							message = "%1 is not a valid pid." />
	<Message id = "PX_INVALID_DATE"							message = "%1 is not a valid date." />
	<Message id = "PX_PMF_DOUBLE_ENTRY"						message = "Deploymentdate file has more than one product %1 with deployment date %2." />
</MessageModule>
