<?xml version = "1.0" ?>
<MessageModule name = "PxDsCB">
	<Message id = "NOT_WRITABLE"  type="user" message = "No premissions to update Broker administration." />
	<Message id = "NOT_LOCAL"     type="user" message = "Broker administration can only be edit from localhost." />
	<Message id = "PXVERSION_MISMATCH"     type="user" message = "Remote ProductXpress Designer version mismatch. Remote version is %1" />
</MessageModule>

