<?xml version = "1.0" ?>
<MessageModule name = "Structure">
	<Message id = "ROLEPLAYEREXISTS"			message = "This %1 already has an association with %2. Please remove this association first before creating a new one." type="user" />
	<Message id = "NO_EMPTYNAME_FEAT"			message = "A feature with an empty name cannot be created" />	
	<Message id = "NO_TD_OPERATION"			message = "Operations cannot be time-dependent"  type="user"/>	
</MessageModule>

