<?xml version = "1.0" ?>
<MessageModule name = "Testset">
	<Message id = "WRONG_METHOD"		message = "Contained Value type does not support this method." />
	<Message id = "DATA_TYPE_ERROR"     	message = "Invalid data type: '%1'" />
	<Message id = "UNINITIALIZED_TEST_VALUE"     	message = "Using uninitialized test value" />
	<Message id = "NOT_A_BATCH_VALUE"     	message = "This is not a batch value" />
	<Message id = "BATCH_VALUE"			message = "Not more than one value allowed." />
	<Message id = "NOT_PRESENT"			message = "'%1' is not present" />
</MessageModule>

