<?xml version = "1.0"  encoding="ISO-8859-1" ?>
<MessageModule name = "FiaStd">
	<Message id = "FUNCFAILED"          message = "Functie fout" />
	<Message id = "REGEXPERROR"         message = "Fout in reguliere expressie '%1': %2" />
	<Message id = "DATATYPE_MISMATCH"   message = "Data types komen niet overeen" />
	<Message id = "UNINITIALIZED_DATA"  message = "Referencie naar ongeïnitializeerde data" />
	<Message id = "GUID_SYNTAX"         message = "Foutive Guid syntax: %1" />
	<Message id = "NO_HEX_DIGIT"        message = "Ongeldig hexa-decimal teken in '%1'" />
	<Message id = "SHORTNAME_TOO_LONG"  message = "Te veel tekens in korte naam: '%1' (max = 21)" />
	<Message id = "SHORTNAME_INV_CHAR"  message = "Ongeldig teken in korte naam: '%1' (moet alpha-numeric zijn)" />
	<Message id = "SHORTNAME_INV_GUID"  message = "Korte naam '%1' kan niet naar guid vertaald worden" />
	<Message id = "COMPRESSION_ERROR"   message = "Compressie fout, %1 geeft '%2' terug" />
	<Message id = "DECOMPRESSION_ERROR" message = "Decompressie fout, %1 geeft '%2' terug" />
	<Message id = "SERIALIZE_ERROR"     message = "Serializatie fout: %1 fout beïndigd" />
	<Message id = "DESERIALIZE_ERROR"   message = "Deserializatie fout: %1 fout beïndigd" />
	<Message id = "DATE_ERROR"   		message = "%1 is een ongeldige datum" />
	<Message id = "DATE_FORMAT_ERROR"   message = "'%1' is een olgeldig datum formaat. Formaat moet %2 zijn" />
	<Message id = "DATE_FORMAT_STRING_ERROR"   message = "'%1' is not a valid date format string. Only %d, %m and %Y are supported." />
	<Message id = "FROM_STRING_ERROR"	message = "'%1' is geen geldige decimale waarde" />
	<Message id = "POWER_ERROR"			message = "Fout in machtsverheffing: power(%1, %2)" />
	<Message id = "LOG_ERROR"			message = "Fout in log expressie: log(%1)" /> 
	<Message id = "LOG10_ERROR"			message = "Fuot in log10 expressie: log10(%1)" /> 
	<Message id = "ILLEGAL_FORMAT"		message = "Fout: Formaat met maximum aantal significantie cijfers toegekent aan RWDecimal" />
	<Message id = "DIV_BY_ZERO"			message = "Deling door nul" />
	<Message id = "OVERFLOW"			message = "Overloop fout" />
	<Message id = "NO_EXP_STRING"		message = "ExpString %1 moet een lengte van 18 hebben. Formaat is Exponent (lengte 3), gevolgd door mantisse (lengte 15), beide voorafgegaan door een teken  (+/-)" />
	<Message id = "YEAR"				message = "&lt;jaar&gt;" />
	<Message id = "MONTH" 				message = "&lt;maand&gt;" />
	<Message id = "DAY"   				message = "&lt;dag&gt;" />
</MessageModule>

