<?xml version = "1.0" ?>
<MessageModule name = "Calculator">
	<Message id = "CALLBACK_FUNC_FAILED" message = "Callback function failed with error: %1" /> 
	<Message id = "CALLBACK_LOOKUP_FAILED" message = "Callback function %1 not found in shared library %2" /> 
	<Message id = "NO_DEPL_NAME" message = "No deployment name present!" /> 
	<Message id = "NO_SHAREDLIB_NAME" message = "No shared library name present!" /> 
	<Message id = "DEPL_DATE_VERSION" message = "Deployment date and version are present!" /> 
	<Message id = "INVALID_CALC_ID" message = "Invalid calculator id (%1)" /> 
	<Message id = "INVALID_DEFINITION_ID" message = "Invalid definition id (%1)" /> 
	<Message id = "NOT_INITIALIZED" message = "Not initialized" /> 
	<Message id = "UNKNOWN_TUPLE_MEMBER" message = "'%1' is not a valid tuple member." />
	<Message id = "INVALID_TUPLE_VALUE_TAG" message = "'%1' is not a valid value tag." />
	<Message id = "INVALID_ATTRIBUTE_VALUE" message = "'%1' is an invalid value for attribute '%2'." />
</MessageModule>
