<?xml version = "1.0" ?>
<MessageModule name = "Calc">
	<Message id = "TIME_IND_ATTR_WITH_ARG"		message = "Use of time independent attribute with argument[%1]"  type="user" /> 
	<Message id = "TIME_IND_ATTR_IN_ATTR_FUNC"  message = "Use of time independent attribute in attributeFunction"  type="user" /> 
	<Message id = "ERROR_IN"					message = "Error in %1"  type="user" />
	<Message id = "INTERNAL_ERROR"				message = "Internal error"  type="user" />
	<Message id = "POLICY_CACHE_BOUND_ERROR"	message = "Error in policy cache boundaries: lower bound = %1, upper bound = %2."  type="user"/>
</MessageModule>
