<?xml version = "1.0" ?>
<MessageModule name = "FiaOMS">
	<Message id = "READ_UNINIT_DATA"          message = "Reading uninitialized data for %1::m_%2" />
	<Message id = "UPDATE_READONLY"           message = "Attempt to update attribute %1::m_%2 but owner is not writable" />
	<Message id = "ATTR_NOT_FOUND"            message = "Attribute not found: %1" />
	<Message id = "CLASS_NO_REGISTERED"       message = "Class %1 not registered in %2" />
	<Message id = "NULL_REFERENCE"            message = "Reference to Null object %1" />
	<Message id = "NO_IMPL_REGISTERED"        message = "No implementation registered for %1" />
	<Message id = "NAMED__OBJ_NOT_FOUND"      message = "Named object '%1' not defined" />
	<Message id = "CREATE_PROXY_UNDUPPORTED"  message = "Creation of objects via remote proxies not supported" />
	<Message id = "NO_URL_FOR"                message = "No URL for %1 in ServerURL.Settings" />
	<Message id = "NO_PROXYMANAGER_SET"       message = "No ProxyManager set" />
	<Message id = "NO_READ_PERMISSION"        message = "Attempt to read attribute %1::m_%2 but owner is not readable" />
	<Message id = "USERNAME_REQUIRED"         message = "Login requires username" />
	<Message id = "PASSWORD_REQUIRED"		  message = "Login requires password" />
	<Message id = "NO_READING_PERMISSION"	  message = "An attempt to perform read without permission" />
	<Message id = "NO_MODIFY_PERMISSION"	  message = "An attempt to perform modify without permission" />
	<Message id = "INVALID_HANDLE"			  message = "Handle initialized with incompatible RefId: %1" />
	<Message id = "NO_SERVER_IMPLEMENTATION"  message = "No server implementation available." />
</MessageModule>

