<?xml version = "1.0" ?>
<MessageModule name = "FunctionEditor">
	<Message id = "NOTALLOWED"          message = "Operation is not allowed on this object." />
	<Message id = "CHILDNOTFOUND"          message = "Child is not found." />
	<Message id = "INDEXOUTOFBOUNDS"          message = "array position index is out of bounds" />
	<Message id = "NOCHILDREN"          message = "Leaf can not have children" />
	<Message id = "NOPARENT"          message = "Tree object does not have a parent." />
	<Message id = "INVALIDTYPE"          message = "Types do not match" />
	<Message id = "INVALIDPXMLMATH"          message = "Begin and end tag of PXMLMath type: %1 do not match" />
	<Message id = "NOTSAVEABLE"          message = "Can not save this type to PXMLMath" />	
	<Message id = "NOTIMPLEMENTED"          message = "Class method is not implemented" />	
	<Message id = "NULL"          message = "Invalid reference called." />	
	<Message id = "NOVIEWCONTEXT"          message = "Drawing operation has no ViewContext." />
	<Message id = "EMPTYGLYPHCONTAINER"          message = "Tree node should have children. No children found." />
	<Message id = "NOCREATE"          message = "Unable to create %1" />
	<Message id = "INVALIDATTRVALUE"          message = "Invalid attribute value %1" />
	<Message id = "INVALIDMODELREF" message = "Invalid reference in symbol to Expression model element"/>
	<Message id = "INVALIDCARETPOS" message = "Attempt to move Caret to invalid position, program will continue"/>
	<Message id = "BADCAST"          message = "Bad cast from %1" />
	<Message id = "INVALIDRETURNTYPE"          message = "no returntype for function %1" type="user"/>
	<Message id = "LIMITNOTFOUND" message = "Could not locate %1 bound argument" />
</MessageModule>

