<?xml version = "1.0" ?>
<MessageModule name = "ExpressionEditor">
	<Message id = "FUNC_EXPR_NO_BASE_SE"
		message = "Non-anchored paths in the expression of a function are not allowed."
		   type = "user" />
	<Message id = "FUNC_EXPR_PATH_FUNC_NOTREACHABLE"
		message = "The function '%1' is not reachable via the path starting from structure element '%2'."
		   type = "user" />
</MessageModule>

