<?xml version = "1.0" ?>
<MessageModule name="MappingWindow">
	<Message id="TARGETS_HEADER"		message="Mapping targets" />
	<Message id="MAPPINGS_HEADER"		message="Mapping" />
	<Message id="MAPS_ONTO"				message="Gets value from" />
	<Message id="NO_SOURCE"				message="&lt;no source for this info&gt;" />
	<Message id="NOT_MAPPED"			message="&lt;not mapped&gt;" />
	<Message id="INVALID_MAPPING"		message="&lt;invalid mapping&gt;" />
</MessageModule>
