<?xml version = "1.0" ?>
<MessageModule name = "TableWizard">
	<Message id = "INVALID_FILECONTENT" message = "An error occurred during import of the table. \nThe format of the choosen file is not valid." type = "user"/>
	<Message id = "INVALID_FILE_TYPE" message = "The file cannot be imported." type = "user"/>
	<Message id = "FILENOTFOUND" message = "The supplied file could not be found." type = "user"/>
</MessageModule>

