<?xml version = "1.0" ?>
<MessageModule name = "ValueEditor">
	<Message id="VALUE" message="Value" />
	<Message id="DATE" message="Date" />
	<Message id="AMOUNT" message="Amount" />
	<Message id="UNIT" message="Unit" />
	<Message id="PERMUTATION_OVERFLOW" message="A range or sequence exceeds the allowed maximum number of values." />
	<Message id="TUPLE_IDENTITY" message="Identity" />
	<Message id="START_DATE" message="Start date" />
	<Message id="END_DATE" message="End date" />
</MessageModule>
