<?xml version = "1.0" ?>
<MessageModule name = "VariableRefactoringWizard">
	<Message id = "CONTEXT_NO_PERMISSION"
		message = "No write permission on deliverable '%1' containing function '%2'. Please make sure you have modify permissions on this deliverable before running the wizard." 
		   type = "user" />
	<Message id = "CONTEXT_NOT_WRITABLE"
		message = "The deliverable '%1' containing function '%2' is not checked-out. Please check-out this deliverable before running the wizard." 
		   type = "user" />
</MessageModule>

