<?xml version = "1.0" ?>
<MessageModule name = "ExtTable">
	<Message id = "EXT_TABLE_NOT_EXIST"   message = "External table data for lid %1 does not exist." type = "user"/>
	<Message id = "EXT_TABLE_EXIST"   message = "External table data for lid %1 already exists." type = "user"/>
	<Message id = "INVALID_TABLE_NAME"   message = "Table name %1 is invalid." type = "user"/>
	<Message id = "INCONSISTENT"   message = "External table deployment configuration contains inconsistencies, try repair option to remove inconsistencies." type = "user"/>
	<Message id = "INVALID_CACHE_SIZE"   message = "Invalid cache size for external table (size = %1)." type = "user"/>
	<Message id = "INCOMPATIBLE_EXTTABLE_VERSION"  message="Incompatible version %1 of external table file %2, it should be %3." type = "user"/>
	<Message id = "CANNOT_CLEAR_CACHE_WHILE_AGGREGATING"  message="Cannot clear calculator cache when there are active aggregations." type = "user"/>
</MessageModule>

