<?xml version = "1.0" ?>
<MessageModule name = "InputMappingEditor">
	
	<Message id = "NAME_JOINSET_1"				message = "Set 1: " />
	<Message id = "NAME_JOINSET_2"				message = "Set 2: " />
	<Message id = "NAME_JOIN_ELEM"				message = "Join: " />

	<Message id = "MAPPED_ON_EXTERNAL"			message = "External" />
	<Message id = "ERROR_IN_CELL"				message = "Error" />

	<Message id = "FAULT_MAP_ON_EXTERNAL"		message = "Error while mapping on external (%1)&#10;%2" />
	<Message id = "FAULT_MAP_ON_TARGET"			message = "Error while mapping on target (%1)&#10;%2" />
	<Message id = "FAULT_MAP_ON_CONSTANT"		message = "Error while mapping on constant (%1)&#10;%2" />
	
	<Message id = "UNTITLED_ELEMENT"			message = "&lt;untitled element&gt;" />
	<Message id = "DANGLING_VALUEDEF"			message = "Dangling value definition" />

</MessageModule>
