<?xml version = "1.0" ?>
<MessageModule name = "SQLite">
	<Message id = "SQLITE_ERROR"
		message = "sqlite3 database error %1 occured in %2: %3%4"/>
	<Message id = "SQLITE_BATCH_ERROR"
		message = "sqlite3 database error %1: %2 query: %3"/> 
	<Message id = "STMNT_NOT_CLOSED"
		message = "sqlite3 usage error: statement not closed"/> 
	<Message id = "STMNT_NOT_ACTIVE"
		message = "sqlite3 usage error: no statement active"/> 
	<Message id = "UNEXPECTED_DBTYPE"
		message = "Unexpected database data-type: %1"/> 
</MessageModule>

