<?xml version = "1.0" ?>
<MessageModule name = "StructureElementEditor">
	<Message id = "VALDEFNOTFOUND"				message = "The selected value definition could not be found in the repository" />
	<Message id = "VARIABLENOTCREATED"			message = "A new Variable could not be created" />
	<Message id = "VARIABLEMAPPINGNOTCREATED"	message = "A new Variable Mapping could not be created" />
	<Message id = "SCALARMAPPINGNOTCREATED"		message = "A new Scalar Mapping could not be created" />
	<Message id = "SELECTEDNOTVAR"				message = "The selected item for is not a variable" />
	<Message id = "NOT_A_CONSTRAINT"			message = "The selected item in the list is not a constraint" />
	<Message id = "NOCONSTRAINTADDED"			message = "A new constraint could not be added" />
	<Message id = "NOPRINCIPALMAPPING"			message = "A principal mapping slice is not available" />
</MessageModule>
