<?xml version = "1.0" ?>
<MessageModule name = "CalculatorCommon">
	<Message id = "INVALID_DEFINITION_ID" message = "Invalid definition id (%1)" /> 
	<Message id = "ALREADY_INITIALIZED" message = "Already initialized" /> 
	<Message id = "DEFINITION_NOT_FOUND" message = "Definition of instance '%1' not found" /> 
	<Message id = "FEATURE_NOT_FOUND" message = "Feature with id '%1' not found" /> 
	<Message id = "NOT_ALLOWED_WITH_OPEN_SESSIONS" message = "Not allowed when sessions are open" />
	<Message id = "CANNOT_CLEAR_CACHE_WHILE_AGGREGATING"  message="Cannot clear calculator cache when there are active aggregations." type = "user"/>
</MessageModule>
