<?xml version = "1.0" ?>
<MessageModule name = "Expression">
	<Message id = "RECURSION_OVERFLOW"		message = "Recursion too deep(%1). In function '%2'" type="user" />
	<Message id = "OCCURRED_IN_FUNCTION"	message = " In function '%1'" type="user" />
	<Message id = "ERROR_IN_FUNCTION"		message = "Error in function '%1'" type="user" />
	<Message id = "NO_VAR_VALUE"			message = "No value found for variable '%1'.%2" type="user" />
	<Message id = "ENDLESS_RECURSION"		message = "Endless recursion. In function '%1'" type="user" />
	<Message id = "ERROR_IN_EXPRESSION" 	message = "Error in expression." type="user" />
	<Message id = "ERROR_IN_FUNCDEF"		message = "Error in definition of function '%1'" type="user" />
	<Message id = "FUNCTION_ID_UNDEFINED"	message = "Function not found: %1" type="user"/>
	<Message id = "AGGR_ADD_FUNC_ERROR"		message = "Cannot add function '%1' to aggregation." type="user" />
	<Message id = "NO_CALCDATE"			    message = "Calculation date missing" type = "user" />
	<Message id = "NO_FUNCVAR_VALUE"		message = "No value found for function variable '%1', arguments: %2.%3" type="user" />
	<Message id = "INTERNAL_ERROR_IN_OPTIMIZATION"	message = "Internal error in optimization." type="user" />
	<Message id = "AGGR_ADD_FUNC_ERROR_FUNCVAR"		message = "Cannot add function '%1' to aggregation: cannot determine dependency for '%2'." type="user" />
	<Message id = "AGGR_ADD_FUNC_ERROR_VARASSIGN"	message = "Cannot add function '%1' to aggregation: uses assignment of '%2'." type="user" />
	<Message id = "AGGR_ADD_FUNC_ERROR_TDVAR"		message = "Cannot add function '%1' to aggregation: '%2' is time dependent." type="user" />
	<Message id = "AGGR_ADD_FUNC_ERROR_SOLVEVAR"	message = "Cannot add function '%1' to aggregation: uses solve of '%2'." type="user" />
	<Message id = "AGGR_ADD_DIRECT_DEP_VAR_ERROR"	message = "Cannot add function '%1' to aggregation: expression involving '%2' can not be used in output aggregation." type="user" />
	<Message id = "ERROR_IN_FUNCDEF_CALLED_BY"		message = "Error in definition of function '%1' called by function(s): %2." type="user" />
</MessageModule>

