<?xml version = "1.0" ?>
<MessageModule name = "FeatureWizard">
	<Message id = "VALDEFNOTFOUND"				message = "The selected value definition could not be found in the repository" />
	<Message id = "VARIABLENOTCREATED"			message = "A new Variable could not be created" />
	<Message id = "VARIABLEMAPPINGNOTCREATED"	message = "A new Variable Mapping could not be created" />
	<Message id = "SCALARMAPPINGNOTCREATED"		message = "A new Scalar Mapping could not be created" />
	<Message id = "SELECTEDNOTVAR"				message = "The selected item for is not a variable" />
	<Message id = "NOT_A_CONSTRAINT"			message = "The selected item in the list is not a constraint" />
	<Message id = "NOCONSTRAINTADDED"			message = "A new constraint could not be added" />

	<!-- input mapping editor -->
	<Message id = "NAME_JOINSET_1"				message = "Set 1: " />
	<Message id = "NAME_JOINSET_2"				message = "Set 2: " />
	<Message id = "NAME_JOIN_ELEM"				message = "Join: " />

	<Message id = "MAPPED_ON_EXTERNAL"			message = "External" />
	<Message id = "ERROR_IN_CELL"				message = "Error" />

	<Message id = "FAULT_MAP_ON_EXTERNAL"		message = "Error while mapping on external (%1)&#10;%2" />
	<Message id = "FAULT_MAP_ON_TARGET"			message = "Error while mapping on target (%1)&#10;%2" />
	
	<Message id = "UNTITLED_LINK"				message = "&lt;untitled link&gt;" />
	<Message id = "UNTITLED_ELEMENT"			message = "&lt;untitled element&gt;" />
</MessageModule>

