<?xml version = "1.0" ?>
<MessageModule name = "Publish">

	<Message id = "NO_TEMPLATE_DIR"
		message = "No value declared for 'TemplatesDir' in configuration file 'Publish.Settings." />

	<Message id = "FILE_MISSING"
		message = "No file named '%1' found."
		type = "user" />

	<Message id = "OUTDOC_MULTIPLE_ROOTS"
		message = "Resulting document cannot have more than one document element."
		type = "user" />

	<Message id = "EVAL_COMP_NOT_FOLDER_STRUCT_ELM"
		message = "Component to evaluate must be a folder or structure element."
		type = "user" />

</MessageModule>
