<?xml version = "1.0" encoding="ISO-8859-1" ?>
<MessageModule name = "ResManXML">

	<Message
		id		= "UNKNOWN_RM_ELEMENT"
		message	= "Unknown Resource Manager element &lt;%1&gt;."
	/>
	<Message
		id      = "RMTAG_NEEDS_REFLIST"
		message = "A Resource Manager &lt;%1&gt; element needs the ref-list attribute."
	/>

	<Message
		id      = "RMTAG_NEEDS_TIMEREFLIST"
		message = "A Resource Manager &lt;%1&gt; element needs the time-ref-list attribute."
	/>

	<Message
		id		= "RM_NEEDS_DATEGEN"
		message = "A Resource Manager &lt;%1&gt; element needs a date generating parent."
	/>

	<Message
		id		= "FROM_ALREADY_SPECIFIED"
		message	= "From-date was already specified before."
	/>

	<Message
		id		= "TO_ALREADY_SPECIFIED"
		message	= "To-date was already specified before."
	/>

	<Message
		id		= "NROFSTEPS_ALREADY_SPECIFIED"
		message	= "NumberOfSteps was already specified before."
	/>

	<Message
		id		= "STEPSIZE_ALREADY_SPECIFIED"
		message	= "Step size was already specified before."
	/>

	<Message
		id		= "STEPUNIT_ALREADY_SPECIFIED"
		message	= "Step unit was already specified before."
	/>

	<Message
		id		= "ILLEGAL_DATEGEN_COMBINATION"
		message = "Exactly two out of 'From', 'To', and 'NumberOfSteps' must be specified."
	/>

	<Message
		id		= "UNNAMED_ELEMENT"
		message = "A Temple &lt;%1&gt; element needs a name attribute."
	/>

	<Message
		id		= "TEMPLATE_NOT_FOUND"
		message = "Could not find named template '%1'."
	/>

	<Message
		id		= "PARAMETER_SUPPLIED_TWICE"
		message = "Parameter '%1' was already given a value."
	/>

</MessageModule>
