<?xml version = "1.0" ?>
<MessageModule name = "Security">
	<Message id = "INVALID_USERNAME"   message = "The user name (%1) is invalid." type = "user"/>
	<Message id = "INVALID_USERGROUPNAME"   message = "The user group name (%1) is invalid." type = "user"/>
	<Message id = "INVALID_FEATURENAME"   message = "The feature name (%1) is invalid." type = "user"/>
	<Message id = "USER_PASSWD_INCORRECT"   message = "The user name or the password is incorect." type = "user"/>
	<Message id = "USER_INCORRECT"   message = "The user name is incorect." type = "user"/>
	<Message id = "USER_EXISTS"   message = "A user with the name (%1) already exists." type = "user"/>
	<Message id = "USERGROUP_EXISTS"   message = "A user group with the name (%1) already exists." type = "user"/>
	<Message id = "FORMAT_ERROR"   message = "User info format error." type = "system"/>
	<Message id = "ENCRYPTION_FAILED" message = "Encryption failed (%1).&#xA;Details: %2" type = "system"/>
	<Message id = "FEATURE_NAME_INVALID" message = "Feature name (%1) is not a valid name." type = "system"/>
	<Message id = "FEATURE_EXISTS" message = "Feature (%1) already registered" type = "system"/>
	<Message id = "FEATURE_NOT_EXIST" message = "Feature (%1) is not registered" type = "system"/>
	<Message id = "USER_ALREADY_ACCESS"   message = "User (%1) has already access to feature (%2)." type = "user"/>
	<Message id = "USER_ALREADY_NO_ACCESS"   message = "User (%1) has no access to feature (%2)." type = "user"/>
	<Message id = "USER_ALREADY_IN_GROUP"   message = "User (%1) is already part of user group (%2)." type = "user"/>
	<Message id = "USER_NOT_IN_GROUP"   message = "User (%1) is not part of user group (%2)." type = "user"/>
	<Message id = "USERGROUP_NOT_EXIST" message = "User group (%1) does not exist" type = "system"/>
	<Message id = "USERGROUP_ALREADY_ACCESS"   message = "User group (%1) has already access to feature (%2)." type = "user"/>
	<Message id = "USERGROUP_ALREADY_NO_ACCESS"   message = "User group (%1) has no access to feature (%2)." type = "user"/>
	<Message id = "INCORRECT_XML"   message = "The security request contains invalid XML: %1" type = "user"/>
	<Message id = "REQUEST_FORMAT_ERROR"   message = "The security request is incorrect" type = "user"/>
	<Message id = "LOGON_FAILED"   message = "Logon failed for user %1" type = "user"/>
	<Message id = "CHANGE_PASSWORD_FAILED"   message = "Change password failed for user %1" type = "user"/>
	<Message id = "NOT_LOGGED_ON"   message = "User is not logged on" type = "user"/>
	<Message id = "NO_USER_WITH_ACCESS" message = "There is no user defined with rights to change the access configuration" type = "user"/>
</MessageModule>

