<?xml version = "1.0" ?>
<MessageModule name = "CalcData">
	<Message id = "CD_NOTIMPLEMENTED"          message = "Not implemented" />
	<Message id = "CD_WRONGTAG"					message = "Xml tag %1 not expected in this state" />
	<Message id = "CD_VARADDEDTWICE"			message = "Variable with lid %1 was already added" />
	<Message id = "CD_VARNRNOTPRESENT"			message = "Variable with zero based index %1 not present. Set contains %2 elements." />
	<Message id = "CD_VARLIDNOTPRESENT"			message = "Variable with lid %1 not present." />
	<Message id = "CD_PARWRONGTYPE"				message = "Parameter type %1 illegal. May not be time-dependent." />
	<Message id = "CD_PARADDEDTWICE"			message = "Parameter with lid %1 was already added" />
	<Message id = "CD_PARNRNOTPRESENT"			message = "Parameter with zero based index %1 not present. Set contains %2 elements." />
	<Message id = "CD_PARLIDNOTPRESENT"			message = "Parameter with lid %1 not present." />
	<Message id = "CD_ERROR"			message = "%1" />
	<Message id = "CD_NOTFOUND"			message = "%1 not found" />
	<Message id = "CD_ADDEDTWICE"			message = "%1 was already added" />
	<Message id = "CD_FIXEDMEMBER"			message = "StartDate and EndDate members cannot not be removed in a Time-Dependent Tuple" />
	<Message id = "CD_NOTPERMUTATED" 			message = "nrOfPermutations method may only be called on a permutated TestSet." />
</MessageModule>

