<?xml version = "1.0" ?>
<MessageModule name = "Val">
	<Message id = "WRONG_METHOD"		message = "Contained Value type does not support this method." />
	<Message id = "DATA_TYPE_ERROR"     message = "Invalid data type: '%1'" />
	<Message id = "NO_SINGLE_DATA"     message = "Scalar does not contain one data element" />
	<Message id = "WRONGINDEXJOIN"	message = "Join must have index 0 (set1), 1 (set2) or 2 (joinSet)" />
	<Message id = "WRONGINDEXTDSCALARELEM"	message = "TimeDependent Scalar element must have index 0 (date) or 1 (value)" />
	<Message id = "WRONGINDEXTDSETELEM"	message = "TimeDependent Set element must have index 0 (begin date), 1 (end date) or 2(value)" />
	<Message id = "USE_END"	message = "Call only allowed when initialized with begin() and while end() returns false" />
	<Message id = "WRONGTYPE"	message = "Error: Value with FPMDataType '%1' and FiaStd DataType '%2'" />
</MessageModule>

